### PR TITLE
Remove restriction on CollectionLike types

### PR DESCRIPTION
**Pull request by rdegnan**
Now that R2DBC 1.0M6 supports array types, allow CollectionLike types to be handled in EntityRowMapper. I verified that this works for both arrays and collection types such as List<String>.

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks a lot. The mentioned restriction originates from a different context. In Spring Data JDBC we map collections of items to a JOIN table. Leveraging database support for collection-like column types makes sense for R2DBC. We haven't really considered supporting relations (JOINs) through object mapping yet as we need to provide more fundamental functionality first.

@schauder we might want to reconsider the mentioned assumption to support collection-typed columns for simple types in Spring Data JDBC.

**Comment by mp911de** [comment]
Depends on #24 as we need integration tests. Enabling this feature will unblock reading of collections but we need also a possibility to store array/collection values. I filed #26 to track writing of collections/arrays.

**Comment by schauder** [comment]
This also relates with https://jira.spring.io/projects/DATAJDBC/issues/DATAJDBC-259 which is about storing collections of primitive types, but the expectation is that they get stored just as an entity with a single property.

How about supporting them via conversions? By registering a CustomConverter for Collection<primitive> it becomes a simple type. 
We might need a way to slap additional information to a conversion though, since I expect it might affect SQL generation.

This in turn is similar/related to https://jira.spring.io/browse/DATAJDBC-239 and https://jira.spring.io/projects/DATAJDBC/issues/DATAJDBC-284

**Comment by mp911de** [comment]
Thanks, @rdegnan for your pull request. I incorporated your change in #31 that also contains conversion and write support for array-typed columns.

Closing this pull request.

**Pull request closed without merging**
