### PR TITLE
Add tests for create and drop statements.

### PR DESCRIPTION
**Pull request by fjacobs**
Implemented tests to prevent: https://github.com/spring-projects/spring-data-examples/pull/545

### CODE REVIEW

**Comment by mp911de** [comment]
Care to elaborate on the background of the tests and what use-case they should cover?

**Comment by fjacobs** [comment]
Background: 
It's possible to create or drop a table by passing a SQL statement to DatabaseClient::execute  and return the number of affected rows as a result by subsequently calling fetch() and rowsUpdated(). In spring-data-r2dbc version RC1 in combination with the Postgres driver this causes unexpected behavior since rowsUpdated() will return a NULL to it's subscriber. In the current snapshot version this issue is not present anymore.

Test use-cases:

The executeDropTable() calls the DatabaseClient execute method with a drop table statement and asserts that the returned value from rowsUpdated() is 0 (and thus not NULL or 1). The assertion that follows will check if the table was actually dropped by calling a SELECT statement which will expect to throw a BadSqlGrammarException since the table should not exist.

The executeCreateTable() first drops the table that was inserted by the before() method. It will then start the actual test by calling the DatabaseClient execute method with a create table statement and asserts that the returned value from rowsUpdated() is 0 (and thus not NULL or 1). It will then check if the table exists by calling a SELECT statement that will expect to throw a EmptyResultDataAccessException since the table exists and is empty.


To improve code readability instead of asserting  Exceptions I wanted to retrieve the table by it's name through DatabaseMetaData::getTables(..). and calling it's resulting rs.next(). I found that in the case that the table doesn't exist,  it depends on the DB vendor whether next() returns false or throws an exception. Also the table name could either be lower or uppercase. I felt this would increase loc and complexity.

I also thought about checking the exception with something like: `assertThatExceptionOfType(BadSqlGrammarException.class).isThrownBy(() -> {	execute("SELECT id, name, manual FROM legoset");})													.withMessageMatching("(doesn't exist|does not exist|not found)");`

 to make it more clear that the assertion is checking for the existence of the table.

**Comment by mp911de** [comment]
Thanks for your explanation. There's an underlying issue which is that the outcome of affected rows count depends on the underlying database. Neither R2DBC nor Spring Data guarantees what should happen when a table gets created or dropped. A database could easily return on `DROP` the number of rows that were within the table.

The only thing guarantee of `rowsUpdated(…)` is that `Mono<Integer>` will always emit a single value. We don't have a test specifically for emitting always a value. It makes sense to add such a test case but that should be one that is a unit test to guarantee well-defined behavior instead of relying on various database drivers.

Care to rewrite your tests into a single unit test? `DefaultDatabaseClientUnitTests` would be a good place for such a test.

**Comment by fjacobs** [comment]
@mp911de I added the unit test. Is it okay?

**Comment by fjacobs** [comment]
@mp911de I added the unit test. Is it okay like this?

**Comment by mp911de** [comment]
Looks good. Let me take it from here.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
