### PR TITLE
RowExtensions.kt added

### PR DESCRIPTION
**Pull request by vlipovetskii**
<reified T> Row.getOrNull extensions added

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@vlipovetskii Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-r2dbc&pullRequestId=217)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-r2dbc&pullRequestId=217) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mp911de** [comment]
Thanks for your contribution. This extension affects R2DBC SPI and not Spring Data R2DBC. Therefore, it does not belong to this project. I suggest that you host the code in a separate repository. 

Having Kotlin extensions for R2DBC is a decent idea. They could be accompanied by Coroutine extensions and `bind` extensions for `Statement.bindNull(…)`.

/cc @sdeleuze

**Comment by sdeleuze** [comment]
@mp911de Do you think those extensions should belong to a dedicated R2DBC project or contributed in https://github.com/r2dbc/r2dbc-spi ?

**Comment by mp911de** [comment]
I think we should follow the same model as for JDBC and put them into a similar place where JDBC Kotlin extensions are hosted.

**Pull request closed without merging**
